### ISSUE TITLE
run commands between iterations

### ISSUE THREAD

**Issue by tcmoore3** [ctk3b/msibi#4]
We need to write in a way to run specific commands between each iteration. Two specific examples of this being useful are 1) moving (either renaming or deleting) files from previous runs (thermo data, trajectory, etc..) and 2) running some sort of analysis on a particular system (e.g., calculate the tilt angle of a monolayer query simulation).

**Comment by ctk3b** [comment]
Well in theory this could be written into the end of your specific run scripts, for hoomd at least - probably not as easily done for gromacs and lammps.

1. Do you mean making backups? That sounds useful to have generally.
2. Do you mean to show how those metrics evolve with the potential? This could conceivably be coupled with 1) if we make the backups using a predictable naming scheme (e.g. how gromacs does it). Then it's up to the user to run the analysis on all the query trajectories that are produced and backed up. Or is there some scenario where you would use this information to alter the next iteration?

I'm not sure it would be simple to generalize the ability to inject something like this at each iteration. Just saving all relevant information at each iteration and leaving it up to the user to post-process should work, right?

**Comment by tcmoore3** [comment]
So yeah, the ability to make backups is one reason to add this in. I was also thinking having the ability to show how certain metrics evolve with the potential. I don't currently see the potentials being updated based on some metric besides the RDF, so I like the idea of renaming things in gromacs-like manner, as it makes it would make it easy to go through and do your analysis separate from the optimization. Saving a series of trajectories could possibly lead to disk-space issues, but I don't see that being a problem in the near future. 

I think we should move forward with this: add a flag to the State class that specifies whether or not that state should save the trajectories, and then iteratively back up the trajectories if that is set to "save."

**Comment by ctk3b** [comment]
Sounds good. 

Probably also a good idea to do this for log files. Should be simple if we have all the workers write to the same filenames, e.g. `log.txt` or `engine.log`.

**Comment by tcmoore3** [comment]
Agreed. Those names are currently not set by the user, which makes it easy to back up.
