### ISSUE TITLE
proper cluster management

### ISSUE THREAD

**Issue by tcmoore3** [ctk3b/msibi#5]
need to figure out how to intelligently 1) figure out how many simulations can be run simultaneously (e.g., number of GPU cards available) and 2) launch this many query simulations.

**Comment by ctk3b** [comment]
Apparently `nvidia-settings` is a command for most unix systems that gies a lot of this information https://gist.github.com/matpalm/9c0c7c6a6f3681a0d39d

**Comment by tcmoore3** [comment]
`nvidia-smi -L` gives a nice, simple output that is easy to parse. Using this for now to grab the available cards.
