### ISSUE TITLE
calculate separate RDFs in parallel

### ISSUE THREAD

**Issue by tcmoore3** [ctk3b/msibi#6]
What would be the best way to go about this? MDTraj compute_rdf() takes a trajectory and only a array of pairs, so without modifying that function (I don't see that being very difficult), we'd still have to read in each trajectory for each pair that gets updated by that state. I can also see just making a multiprocessing pool where each pair is passed being a viable option. 

I'll be working on either one or both of these options tomorrow.

**Comment by ctk3b** [comment]
Right now we're using the multiprocessing wrapper around the threading library (multiprocessing.dummy). I don't think it's possible to just toss in the actual multiprocessing but this would be easy enough to test/Google. Each RDF calculation writes to a unique key in the dictionary, which should somehow make it possible but you need to somehow give each process access to the same dictionary in memory which might not play nice with the GIL.

**Comment by ctk3b** [comment]
On my phone but this seems to address the problem http://stackoverflow.com/questions/12538485/python-multiprocess-update-dictionary-synchronously

**Comment by tcmoore3** [comment]
Working in parallel now using the python multiprocessing module.
