### ISSUE TITLE
Memory issues with new parallel RDF

### ISSUE THREAD

**Issue by tcmoore3** [ctk3b/msibi#7]
When using the new, parallel RDF version of the code, I keep getting issues where I use more memory than I have available. Something doesn't seem right here, since my limit is 40G, I'm using 4 states, where the largest trajectory is 16M. `cpu_count()` returns 16, so the most memory the trajectories should consume is 16*16M << 40G. This may be a bigger issue than we were anticipating. Need to look into profiling to see where the memory is being consumed.

**Comment by ctk3b** [comment]
As a first test, you could just run it single threaded and see how much memory the Python process consumes. It should be a lot more than 16M but 2.5GB sounds like a lot. 

Also one thing we could do is to only store a reference to the trajectory file and then only load / iterload it for the RDF and delete it again after.

**Comment by tcmoore3** [comment]
This issue has been resolved. The RDF calculations are not done in parallel with the fix. However, the memory issue was fixed by adding a ```max_frames``` parameter, which sets a max number of frames to load in at once from the trajectory.
