### ISSUE TITLE
run fails if rdf directory not in main optimization directory

### ISSUE THREAD

**Issue by tcmoore3** [ctk3b/msibi#9]
right now the update_potential is looking in the rdfs/ directory for the RDFs to use in the update step. if that directory does not exist, the run fails due to a IOError: [Errno 2] No such file or directory:... error.

**Comment by ctk3b** [comment]
Isn't that where we're assuming the targets will always be? If so, we can just add a check in the initialize step

**Comment by tcmoore3** [comment]
Yeah, easy check; put it here more so I don't forget about it tomorrow.

**Comment by tcmoore3** [comment]
Fixed in commit 9b48145b45dfb2467dec0ddb75e70c45c749858d
